//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Themis
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "tmpd";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"Themis";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Sławomir Aleksiuk";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID ThemisDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(ThemisCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID ThemisExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(ThemisCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewThemisExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(ThemisCommandSetId), 0x0001);
	
		// Package identifier
		public const string ThemisPackageId = "1d69e8bc-61e7-44d0-9b8d-289c8b4afdfc";
		
		// Editor factory identifier
		public const string ThemisEditorFactoryId = "303d514b-71d6-4416-834c-801128e7880b";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string ThemisModelExplorerToolWindowId = "3a1e3533-678b-4a06-965a-a35a748ac5fd";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Themis
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string ThemisCommandSetId = "94bfcb0d-6064-4d53-a235-5f35cb74f7d4";
	}
}